### PR TITLE
Pan to and pan to shape

### PR DESCRIPTION
**Pull request by ggomez91**
Hello, I implemented a couple of functions to enhance panning:

**panTo(x, y)** : Centers the view to a point in drawing coords
**panToShape(shape)**: Centers the view to a given shape

This would satisfy [#446](https://github.com/literallycanvas/literallycanvas/issues/446)

### CODE REVIEW

**Comment by irskep** [comment]
It's cool that you did this, but it's going to cause an issue once #511 is merged. However, I personally have never tried #511, as much as I want it to succeed. What do you think I should do?

**Comment by ggomez91** [comment]
I personally think #511 is important for the future of the library. It will really allow more contribution. 
I am no expert in Git but is there any reason to keep the new ES code in the same repo? Maybe a fork would be better and then we could implement features in parallel until the ES version is out.

**Comment by ggomez91** [comment]
Hello @irskep 
I've cloned  **Progymedia:convert-to-es6-and-jsx** and it builds and works wonderfully.
What do you think on merging https://github.com/literallycanvas/literallycanvas/pull/511 into a new branch and finish the pending tasks in there and in the mean new functionality can happen there as well. 

Merging this new branch to master would happen when the tasks are finished and then main development would come back to master.

This way others (like myself) can contribute to the new branch and finish Decaffeination sooner.

**Comment by mjameswh** [comment]
@ggomez91 I totally agree. See my more elaborate response in #511.

**Pull request closed without merging**
