### PR TITLE
Refactor Tools (Remove React)

### PR DESCRIPTION
**Pull request by MandaBrown**

### CODE REVIEW

**Comment by MandaBrown** [comment]
Oops. Apologies!

**Comment by irskep** [comment]
For a second, I was like "What!? removing all the tools?"

Out of curiosity, what are you using Literally Canvas for?

**Comment by MandaBrown** [comment]
Ha! An interactive whiteboard. We want the parent application to take care of the tool rendering, which might look pretty different for teachers/students (and also from what is currently there), and not to use react. :)

Thank you so much for the library! We're having a lot of fun with it. <3

**Comment by MandaBrown** [comment]
If you're curious, we've had some good success this afternoon with a copy of the library without react or the tool gui, and just using text links in our app to switch tools & change some basic options. I added a setStrokeWidth method to lc, so we could use it like setTool... which I'm not sure yet is the right approach.

**Comment by MandaBrown** [comment]
Thinking of contributing back as we can, although we'd have to pick pieces out at this point. Also thinking of making a separate public repo of our version, maybe `JustCanvas`?

**Comment by irskep** [comment]
I could see us doing a no-tools build, no need for a separate project. "Literally Canvas Core" maybe.

Instead of adding a `setStrokeWidth`, I'd recommend firing an event in the GUI and listening for it in the tool. Look at how the text tool listens for the `setFont` event (particularly where it subscribes and unsubscribes): https://github.com/literallycanvas/literallycanvas/blob/master/src/tools/Text.coffee

The GUI just calls `@props.lc.trigger 'setFont', fontString`. Eventually I want all tools to work like this.

**Comment by irskep** [comment]
(The tool and the GUI for the tool are tightly coupled, so I don't want to add new methods to the `lc` object just to support new kinds of options.)

**Comment by MandaBrown** [comment]
That makes total sense!!! Thanks so much.

Any thoughts on how you might want to integrate a no-tools build into this project? I'd love to help with "Literally Canvas Core". :)

**Comment by irskep** [comment]
Most of the work is already done! I've been careful to keep the React-dependent code in a box. I suspect all you'd need to do is add one CoffeeScript file and a gulp action.

The starting point I would use is to copy this file as `lc-core.coffee` (in the same directory) and just delete the `initReact` lines (convenient, eh?) and the code that creates DOM elements to host React stuff (`pickerElement`, `optionsElement`).

Then rename the `browserify` gulp action to `browserify-lc-main` and make a new one, `browserify-lc-core`. I'm sure you can figure out the rest.

The hard part of this is actually the documentation and distribution.

**Comment by MandaBrown** [comment]
Awesome, I'd like to give this a shot! Sounds pretty much like what we did (except that we went to the extreme of entirely removing the React bits. You did do a great job of keeping that contained! 

I don't see any contribution-specific guidelines on the repo - anything I should keep in mind? Are you interested in getting code & documentation PRs? I don't want to accidentally give you unwanted puppies, if reviewing & merging stuff like that isn't something you want to do right now. :)

**Comment by irskep** [comment]
I will be happy to write contributor guidelines if you tell me what would be helpful to know. :-) I have had surprisingly few regular contributors, so it hasn't come up before.

For docs, you can just include descriptions of new features in the pull request text, and I'll integrate them into the docs repo. Of course you could also open a PR against the `sphinx` branch of the docs, but I don't imagine you want to learn Sphinx and set up the doc build system, unless you already know the Python ecosystem.

If you can get the build system to produce a second file that just includes the core stuff, without major disruption to the rest of the code or changing the existing API, I will find a way to merge it. No unwanted puppies here!

**Comment by MandaBrown** [comment]
I'm ok without additional guidelines; I mostly wanted to make sure that contributions are currently wanted. :)

I'll work on this very soon!

**Pull request closed without merging**
