### PR TITLE
Switch to react-based rendering

### PR DESCRIPTION
**Pull request by idolize**
See #355 

~~**Includes a breaking change**~~

~~Support for the synchronous API–returning an instance of `LiterallyCanvas` from `init()`–is no longer possible because we must wait for React to render the component and flush to the DOM (which, unlike the raw DOM api, is not synchronous).~~

### CODE REVIEW

**Comment by idolize** [comment]
Note: I also updated the dependencies and updated the React code to be current with the existing API (no `React.addons` and usage of `ReactDOM`) so there are no more deprecation warnings printed to the console and it will be more future-proof.

**Comment by irskep** [comment]
That breaks waaaaay too much stuff. Like, 90% of existing usage. `onInit()` really only exists for the jQuery API. As far as I know, few people use it.

Surely there is a way to force React to render the DOM initially?

**Comment by idolize** [comment]
Fair enough :) I'll add back the old code path and clean it up some.

Unfortunately I don't think there is any way to synchronously get a DOM
node from a "cold" React render, because React batches DOM updates behind
the scenes.

**Comment by irskep** [comment]
I think this can be saved by splitting up the `LiterallyCanvas` init process into 2 parts: instantiation and attachment to the DOM. Then you can immediately return the object without a render having happened yet. Might still cause problems, though...I'll think about it.

**Comment by idolize** [comment]
@irskep Updated! Now non-breaking :laughing: 

Yeah, I think you're right: there is probably a more elegant way to structure things and revamp the API (but I didn't want to get into a major refactor with this PR).

**Comment by irskep** [comment]
This looks like it mostly works, but it has two problems.

Problem #1: there's a lot of duplicate code. Specifically:
  * Option defaults
  * Enumeration of the tools to create elements
  * Toolbar top/bottom decision

This seems to be caused by problem #2: the old GUI initialization code path is still intact. I suspect you did this because of our discussion about not breaking the return value of `LC.init()` but it still seems wrong. I would much rather have `LC.init()` driven by usage of the React component.

In any case, I'm going to clone this branch and see if I can find a solution I like. At the very least, we will end up with a usable React component and your gulpfile changes.

**Comment by irskep** [comment]
BTW, next time, please consider submitting a PR from a non-master branch. I feel nervous about cloning people's master branches because usually they just track the upstream repo's master.

**Comment by irskep** [comment]
(And thanks for doing this!)

**Comment by irskep** [comment]
Replacing this with #364

**Pull request closed without merging**
