### PR TITLE
Update package.json to React 15.0

### PR DESCRIPTION
**Pull request by arian**
Literallycanvas cannot be used alongside the newer react 15.0.

This updates the peerDependency requirement to either 0.14 or 15.x.

There is no test suite so I can't verify everything, but the demo page seems to work fine without errors.

### CODE REVIEW

**Comment by irskep** [comment]
Sure, why not.

**Comment by rmacklin** [comment]
Could you publish a new release for this?

**Comment by rmacklin** [comment]
@irskep If there's any way you could publish a new release with this change that would be much appreciated. Without a new version literallycanvas can't be used with react 15 because it'll complain that the peerDependency on react is unmet :(

**Comment by irskep** [comment]
Just wanted to say I see this but don't have time right now.

**Pull request merged**
