### PR TITLE
Resolved an issue in which Literally Cavas was eating up mouse events on the HTML document, preventing them from being propagated to the DOM

### PR DESCRIPTION
**Pull request by kremuwa**
The issue was described in #250 . The solution was proposed and implemented by @sevikon

### CODE REVIEW

**Comment by saintthor** [comment]
please, which is the oldest version just after you fixed this bug?

**Comment by kremuwa** [comment]
Guessing from dates of releases, you're looking for v0.4.1: https://github.com/literallycanvas/literallycanvas/releases/tag/v0.4.1

**Comment by saintthor** [comment]
thanks. it is v0.4.2.

**Comment by kremuwa** [comment]
You're right, some mysterious failure happened in my brain and I understood
"just before" instead of "just after" even though you clearly wrote the
latter :). Probably I thought you want the lib in a state prior to the fix.

**Pull request merged**
